### PR TITLE
default-weak-map: new structure

### PR DESCRIPTION
**Pull request by yoursunny**
* [X] Documentation: #133 
* [X] Code the structure
* [X] Add convenience methods (`#.inspect`, `#.toString`, `#.toJSON` etc.)
* [ ] Add proper iterators: infeasible for `WeakMap`
* [ ] Add a static `#.from` function: `DefaultMap` doesn't have it, so I suppose I don't need one
* [X] Add unit tests
* [X] Add proper types
* [X] Add the structure to the endpoint (both js & ts)
* [ ] Add a changelog entry
* [ ] Add keywords

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @yoursunny. Thanks for your PR. It seems like a nice addition. I just have a remark: couldn't we keep the code more DRY by either:

1. creating a factory function taking either `Map` or `WeakMap` and returning the class (with a condition to create or not iterator methods in one of the cases) or
2. only coding the `DefaultWeakMap` constructor and then only copying the `DefaultMap` prototype to it (since the methods' code is basically identical, you can see examples of this in the `trie.js` file).

**Comment by yoursunny** [comment]
Between `DefaultMap` and `DefaultWeakMap`, 3 methods are same:

* peek
* has
* inspect

Other methods are different:

* WeakMap has no clear method, so clear is different
* WeakMap has no size property, so get set delete are different

Do you still want to copy the three methods above?

**Comment by Yomguithereal** [comment]
Ok then I feel the best course of action is to copy the three methods you mention from defaultmap’s prototype. But it feels a bit moot indeed seeing those methods are not very complicated. Copying those methods over also means to require the defaultmap file and make a client bundle slightly larger if you only need the defaultweakmap. So I will let you chose whether to do it or not. Tell me and I will respect your decision and then proceed to merge afterwards.

**Comment by yoursunny** [comment]
I'd rather not copying the method via prototype. They are shorter than five lines.

**Comment by Yomguithereal** [comment]
Fair enough :). Merging right now.

**Pull request merged**
