### PR TITLE
Typo on heap.md

### PR DESCRIPTION
**Pull request by joelwallis**

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Thanks for spotting that @joelwallis. Merging right now.

**Comment by joelwallis** [comment]
Hey @Yomguithereal, thank you for merging :-)

I had another suggestion to make, but I decided to keep the PR simple and focused. I saw that you use simple callbacks to sort Heap items and they should return `-1`, `0` or `1` to define the current item position. I thought that using a more verbose version would be simpler for beginners understanding its behavior. Since data structures are frequent topics on universities, etc., your project might receive some attention from students around the world.

So, for example, the following example snippet:

```js
var heap = new Heap(function(a, b) {
  if (a.priority > b.priority)
    return -1;
  if (a.priority < b.priority)
    return 1;
  return 0;
});
```

could use a more verbose if/else construction like that:

```js
var heap = new Heap(function(a, b) {
  if (a.priority > b.priority) {
    return -1;
  }
  else if (a.priority < b.priority) {
    return 1;
  }
  else {
    return 0;
  }
});
```

There's no logical difference between these two examples, but only that this second one is more verbose - and more close to what students learn in class.

**Comment by joelwallis** [comment]
What do you think? Does it makes sense for you?

**Comment by Yomguithereal** [comment]
@joelwallis If we go this way, why not even add some comments to explain what returning `1` or `-1`, for instance, really means.

**Comment by joelwallis** [comment]
Seems interesting.

I had the feeling that you tried to keep the sorting callback API close to [Array#sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) in your Heap class to keep it familiar to JS developers. Is that correct?

**Comment by Yomguithereal** [comment]
Yes, and because this is usually the way stable sort comparators work in a multitude of different languages. This is the most easy to customize for a wide variety of data. However, it's not that intuitive and requires you to understand, even superficially, how sort algorithms etc. operate.

For instance, it is quite possible to build a comparator to sort on multiple properties but this requires that the developer knows how to do so. So for a while, I was pondering whether to use lodash-like comparator definition (something like [this](https://lodash.com/docs/4.17.4#sortBy)), but this is less powerful and somewhat limiting albeit more easily understandable.

**Pull request merged**
