### PR TITLE
fix(bit-set/vector): wrong size counting when (re)set last bit

### PR DESCRIPTION
**Pull request by PhilippeMorier**
### What
Get the unsigned representation of `newBytes` before updating size in `set()` & `reset()`.

### Why
```JavaScript
var set = new BitSet(32);
set.set(31); // resulted in set.size = -1
```

Due to bit-shifting we get a [signed representation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators#Signed_32-bit_integers). I.e. if we shift `1 >> 31` we get `-2147483648` which then causes problem when we check with `newBytes > oldBytes` if we need to increment `size`.

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @PhilippeMorier. Thanks for your PR. Can the same issue happen with the `#.reset` and `#.flip`  method?

Also, would you be willing to duplicate your fix for the [`bit-vector`](https://github.com/Yomguithereal/mnemonist/blob/master/bit-vector.js)?

**Comment by PhilippeMorier** [comment]
Hey @Yomguithereal, thanks for your prompt response and feedback.

I applied the fix for `flip` and as well for `BitVector`.

Concerning `reset()`, it looks like it is ok, since `~(1 << 31)` returns `2147483647`. I still added some tests.

**Comment by Yomguithereal** [comment]
Thanks for the update @PhilippeMorier. Can I also ask you, before merging and drafting a release to try to run the following:

```
node benchmark/bit-set/performance.js
```

several times with and without your fix and tell me whether you see significant changes?

**Comment by PhilippeMorier** [comment]
FYI: I am currently on a 11 year old laptop :innocent:.

But it looks like there is an increase :cry:. WDYT?

**With** fix:
```
Bits: 1707.505ms
Bits: 1709.268ms
Bits: 1704.908ms
Bits: 1709.506ms
Bits: 1705.405ms
Bits: 1711.486ms
Bits: 1717.428ms
Bits: 1705.335ms
Bits: 1705.968ms
Bits: 1706.362ms
```

**Without** fix:
```
Bits: 1419.127ms
Bits: 1420.810ms
Bits: 1418.113ms
Bits: 1413.796ms
Bits: 1417.594ms
Bits: 1412.181ms
Bits: 1415.982ms
Bits: 1414.998ms
Bits: 1414.780ms
Bits: 1413.147ms
```

**Comment by PhilippeMorier** [comment]
I just tried with `newBytes = Math.abs(newBytes);` and it looks better. WDYT?

With `Math.abs()`
```
Bits: 1559.107ms
Bits: 1554.358ms
Bits: 1553.127ms
Bits: 1553.768ms
Bits: 1556.779ms
Bits: 1556.216ms
Bits: 1551.225ms
Bits: 1552.185ms
Bits: 1553.939ms
Bits: 1550.936ms
```

**Comment by PhilippeMorier** [comment]
Seems like `if (newBytes < 0) newBytes = ~newBytes + 1;` is the fastest. WDYT?

```
Bits: 1519.348ms
Bits: 1534.629ms
Bits: 1519.142ms
Bits: 1527.232ms
Bits: 1517.998ms
Bits: 1517.332ms
Bits: 1521.226ms
Bits: 1522.154ms
Bits: 1519.803ms
Bits: 1520.944ms
```

Ideas from [stackoverflow](https://stackoverflow.com/questions/17062617/fast-and-save-way-to-remove-the-sign-of-a-singed-number-in-javascript).

**Comment by Yomguithereal** [comment]
Hello again @PhilippeMorier. Since we basically now the only case that messes thing up (if pos is 31) we could also test if and see if its faster?

**Comment by PhilippeMorier** [comment]
Do you mean something like this?
```js
if (pos === 31) newBytes = Math.abs(newBytes);
```

**Comment by Yomguithereal** [comment]
Well this is baffling :). Ok, let's go with `Math.abs` for now.

In the beginning I used this comparison trick to cache the size of the bitset (which can be useful since the other method is a sum of the popcount of each integer which is very costly). But this is at the expense of atomic mutator's perf so I might remove this in the future. Is this size caching useful to you in your use cases?

**Comment by PhilippeMorier** [comment]
Yeah, baffling indeed :innocent:.

I will start using `size` but not in a performant critical case.

**Comment by Yomguithereal** [comment]
v0.31.0 is now live on npm. Out of curiosity, can you tell me what your use case is?

**Comment by PhilippeMorier** [comment]
In my case the `BitSet` holds record which 'values' are 'active'. I use `size` to cound how many `values` are 'active'. I have a lot of these record-`BitSet`s, so it is convenient to have the `size` property.

**Pull request merged**
