### PR TITLE
Add TrieMap.update

### PR DESCRIPTION
**Pull request by wholenews**

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @wholenews. This seems nice but could you show a use case of when you would like to use this `#.update` method?

**Comment by wholenews** [comment]
Hello @Yomguithereal,

The case that I'm working on involves articles with hierarchical categories like "sports,basketball,college".  When a new article is seen I want to increment the count for the corresponding category:

```trieMap.update(item.category, (v) => (v || 0) + 1)```

Then later I might query for "What are all the subcategories of sports with at least 10 articles".

Without the patch you need to:
```
const currentValue = trieMap.get(item.category) || 0
trieMap.set(item.category, currentValue+1)
```

Which I tried first, but unsurprisingly it is quite noticeably slower.

I think many of the other data structures could benefit from a similar update function.  I'm not sure if `update((oldVal: V) => V)` is the best interface, but it works for me.  Thanks for great package!

**Comment by Yomguithereal** [comment]
@wholenews seems like a nice addition indeed. Can I ask you to add a unit test for the method as well as its documentation on the `gh-pages` branch before I merge the PR please?

**Comment by Yomguithereal** [comment]
Thanks @wholenews. Merging right now.

**Comment by Yomguithereal** [comment]
Released as v0.38.0

**Pull request merged**
